name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'doc/**'
      - 'src/pretix/locale/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'doc/**'
      - 'src/pretix/locale/**'

permissions:
  contents: write  # Erforderlich zum Auschecken des Codes
  packages: write  # Erforderlich zum Pushen in die GitHub Registry

env:
  FORCE_COLOR: 1

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Packaging
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install system dependencies
        run: sudo apt update && sudo apt install -y gettext unzip
      - name: Install Python dependencies
        run: pip3 install -U setuptools build pip check-manifest
      - name: Run check-manifest
        run: check-manifest
      - name: Run build
        run: python -m build
      - name: Check files
        run: unzip -l dist/pretix*whl | grep node_modules || exit 1

  docker-build:
    runs-on: ubuntu-22.04
    needs: test
    permissions:
      contents: read
      packages: write  # Erforderlich zum Pushen in die GitHub Registry
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for ARM64
        run: |
          IMAGE_TAG=${{ github.sha }}
          IMAGE_NAME=ghcr.io/${{ toLower(github.repository_owner) }}/pretix:${IMAGE_TAG}

